import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,writeFileSync,readFileSync,rmSync,chmodSync,symlinkSync,linkSync,readdirSync} from 'node:fs';import {join} from 'node:path';import {tmpdir} from 'node:os';import {spawnSync} from 'node:child_process';
import {clientConfig} from '../mcp-client-config.mjs';
function fixture(fn){const d=mkdtempSync(join(tmpdir(),'continuity-client-config-'));try{const pkg=join(d,'package with spaces'),dir=join(d,'private case');mkdirSync(pkg);mkdirSync(join(pkg,'src'));mkdirSync(dir,{mode:0o700});writeFileSync(join(pkg,'package.json'),JSON.stringify({name:'@ramex-labs/continuity-mcp-gateway',version:'0.3.0-preview.7',bin:{'continuity-mcp-gateway':'./src/cli.mjs'}}));writeFileSync(join(pkg,'src/cli.mjs'),'throw Error("must not execute")');const config=join(dir,'gateway.json');writeFileSync(config,'synthetic secret; not JSON: must not be read',{mode:0o600});fn({d,pkg,dir,config,args:['--client','vscode','--gateway-dir',pkg,'--config',config]});}finally{rmSync(d,{recursive:true,force:true});}}
test('prints correct client roots and separate arguments without exposing case contents',()=>fixture(({config,args})=>{for(const client of ['vscode','claude','portable']){const out=clientConfig([args[0],client,...args.slice(2)]);const entry=out[client==='vscode'?'servers':'mcpServers']['continuity-gateway'];assert.equal(entry.args.length,3);assert.equal(entry.args[1],'--config');assert(entry.args[2].endsWith('private case/gateway.json'));assert(!JSON.stringify(out).includes('synthetic secret'));assert.equal(entry.type,client==='vscode'?'stdio':undefined);}assert(readFileSync(config,'utf8').startsWith('synthetic secret'));}));
test('refuses public case file and parent without changing permissions',()=>fixture(({config,dir,args})=>{chmodSync(config,0o644);assert.throws(()=>clientConfig(args),{code:'CONFIG_UNAVAILABLE'});chmodSync(config,0o600);chmodSync(dir,0o755);assert.throws(()=>clientConfig(args),{code:'CONFIG_UNAVAILABLE'});}));
test('refuses symlink and hard-linked case files',()=>fixture(({config,dir,args})=>{const alias=join(dir,'link.json');symlinkSync(config,alias);assert.throws(()=>clientConfig([...args.slice(0,-1),alias]),{code:'CONFIG_UNAVAILABLE'});rmSync(alias);linkSync(config,alias);assert.throws(()=>clientConfig(args),{code:'CONFIG_UNAVAILABLE'});}));
test('rejects missing path, wrong package and unsupported installed version',()=>fixture(({pkg,args})=>{assert.throws(()=>clientConfig([...args.slice(0,-1),join(pkg,'missing')]),{code:'CONFIG_UNAVAILABLE'});for(const metadata of [{name:'other',version:'0.3.0-preview.7'},{name:'@ramex-labs/continuity-mcp-gateway',version:'9.0.0'}]){writeFileSync(join(pkg,'package.json'),JSON.stringify(metadata));assert.throws(()=>clientConfig(args),{code:'GATEWAY_UNAVAILABLE'});}}));
test('rejects duplicate, unknown, incomplete and control-character flags',()=>{for(const a of [[],['--client','vscode'],['--client','vscode','--client','claude','--config','x'],['--client','other','--gateway-dir','x','--config','x'],['--client','vscode','--gateway-dir','x','--config','x\nsecret']])assert.throws(()=>clientConfig(a),{code:'USAGE'});});
test('CLI emits no stdout on refusal and makes no files',()=>fixture(({d,args})=>{const before=readdirSync(d);const result=spawnSync(process.execPath,[new URL('../mcp-client-config.mjs',import.meta.url).pathname,...args.slice(0,-1),join(d,'missing')],{encoding:'utf8'});assert.equal(result.status,2);assert.equal(result.stdout,'');assert.match(result.stderr,/CONFIG_UNAVAILABLE/);assert.deepEqual(readdirSync(d),before);}));
