import {ACTIONS,ROLE_NAMES,defaultCase,parseCase} from './model.js';
const $=id=>document.getElementById(id), el=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;};
let c=defaultCase(),last=null,pinned=null,worker=null,serial=0,playing=false,playEpoch=0,finishPending=null;
const stages=[['Meet the team.','Alex is the original investigator. Bea is a separate identity with separately declared permissions.'],['There is still work to do.','The recorded collection has happened. The review remains open, assigned to Alex.'],['The job gets a new helper.','The recorded handover assigns the unfinished review to Bea. Alex’s old identity is marked terminated in this history.'],['The job survives the handover.','Alex’s original collection permission has also been withdrawn. Bea still has the unfinished job. Try changing a permission below.']];
function option(value,text){const n=el('option',text);n.value=value;return n;}
function actors(select,includeNone=false){select.replaceChildren();if(includeNone)select.append(option(-1,'Not assigned'));c.names.forEach((n,i)=>select.append(option(i,n)));}
function clearResult(message='Choices changed. Check this request to see the new result.'){
 serial++;if(worker){worker.terminate();worker=null;}if(finishPending){finishPending(false);finishPending=null;}last=null;$('pin').disabled=true;$('export-result').disabled=true;$('run').disabled=false;$('result').className='result pending';$('decision').textContent='Ready to try';$('explanation').textContent=message;$('technical').textContent='No current result. Run the changed case.';$('technical-summary').textContent='';$('timeline').replaceChildren();$('agents').replaceChildren();$('duty').textContent='Run the changed case to inspect its work.';$('duty-status').textContent='—';
}
function error(message){clearResult(message);$('result').className='result error';$('decision').textContent='Let’s check that';}
function changed(){playEpoch++;playing=false;$('play').textContent='Play the handover';clearResult();}
function renderForm(){
 $('case-name').value=c.name;$('names').value=c.names.join('\n');$('names').setCustomValidity('');actors($('actor'));$('actor').value=c.actor;$('operation').replaceChildren(...ACTIONS.map((a,i)=>option(i,a[1])));$('operation').value=c.operation;$('withdraw').checked=c.withdrawReview;$('deny').checked=c.deny;$('withdraw').parentElement.lastChild.textContent=`Withdraw ${c.names[1]}’s original review permission`;
 $('roles').replaceChildren();ROLE_NAMES.forEach((name,i)=>{const r=c.roles.find(x=>x.role===i),row=el('div');row.className='role-row';const label=el('label',name+' — assign a role and separate powers');const owner=el('select');owner.setAttribute('aria-label',name+' owner');actors(owner,true);owner.value=r?.agent??-1;const ops=el('select');ops.multiple=true;ops.setAttribute('aria-label',name+' operations');ACTIONS.forEach((a,j)=>{const o=option(j,a[1]);o.selected=r?.operations.includes(j)??false;ops.append(o);});label.append(owner);row.append(label,ops);const update=()=>{c.roles=c.roles.filter(x=>x.role!==i);if(Number(owner.value)>=0)c.roles.push({role:i,agent:Number(owner.value),operations:[...ops.selectedOptions].map(x=>Number(x.value))});changed();};owner.onchange=update;ops.onchange=update;$('roles').append(row);});
 $('grants').replaceChildren();c.grants.forEach((g,i)=>{const row=el('div');row.className='grant-row';const who=el('select');who.setAttribute('aria-label',`Permission ${i+1} helper`);actors(who);who.value=g.agent;const op=el('select');op.setAttribute('aria-label',`Permission ${i+1} operation`);op.append(...ACTIONS.map((a,j)=>option(j,a[1])));op.value=g.operation;row.append(who,op);who.onchange=()=>{g.agent=Number(who.value);changed();};op.onchange=()=>{g.operation=Number(op.value);changed();};for(const [key,title] of [['revoked','Withdraw this permission'],['expired','Already expired']]){const label=el('label');label.className='check';const check=el('input');check.type='checkbox';check.checked=g[key];check.onchange=()=>{g[key]=check.checked;changed();};label.append(check,document.createTextNode(title));row.append(label);}const remove=el('button','Remove');remove.type='button';remove.onclick=()=>{c.grants.splice(i,1);changed();renderForm();};row.append(remove);$('grants').append(row);});
 $('add-agent').disabled=c.names.length>=12;$('add-grant').disabled=c.grants.length>=32;renderStep();
}
function renderStep(){const [title,copy]=stages[c.step];$('stage-title').textContent=title;$('stage-copy').textContent=copy.replaceAll('Alex',c.names[0]).replaceAll('Bea',c.names[1]);$('step-label').textContent=`Step ${c.step+1} of 4`;$('previous').disabled=c.step===0;$('next').disabled=c.step===3;for(const b of document.querySelectorAll('[data-step]')){if(Number(b.dataset.step)===c.step)b.setAttribute('aria-current','step');else b.removeAttribute('aria-current');}}
function showResult(r){last=r;$('run').disabled=false;$('pin').disabled=false;$('export-result').disabled=false;const answer=r.decision==='ALLOW'?'allow':r.decision==='DENY'?'deny':'error';$('result').className='result '+answer;$('decision').textContent=r.decision==='ALLOW'?'Allowed by these rules':r.decision==='DENY'?'Not allowed by these rules':'The answer is not established';const reasons={REVOKED:'The relevant permission was withdrawn.',PROHIBITED:'An explicit stop rule blocks this request.',ACTION_NOT_ALLOWED:'No matching permission allows this operation.',RESOURCE_NOT_ALLOWED:'The permission does not cover this resource.',EXPIRED:'The relevant permission has expired.',AGENT_TERMINATED:'This agent’s identity is terminated in the selected history.'};$('explanation').textContent=`${c.names[c.actor]}: ${ACTIONS[c.operation][1].toLowerCase()}. `+(r.decision==='ALLOW'?'Core found a valid permission for this request.':reasons[r.code]??`Core returned ${r.code??r.decision}. Open the workshop for the exact explanation.`)+' No operation was carried out.';
 $('agents').replaceChildren(...r.agents.map((a,i)=>{const card=el('div');card.className='agent'+(a.status==='TERMINATED'?' ended':'')+(i===c.actor?' selected':'');const face=el('span');face.className='robot';face.setAttribute('aria-hidden','true');card.append(face,el('strong',a.name),el('small',a.status==='TERMINATED'?'Ended in this record':'Active identity'));if(r.duties.some(d=>d.assignee===a.id)){card.classList.add('has-duty');card.append(el('small','▤ Unfinished work assigned'));}const roles=c.roles.filter(x=>x.agent===i).map(x=>ROLE_NAMES[x.role]);if(roles.length)card.append(el('small',roles.join(' · ')));return card;}));
 const duty=r.duties[0],owner=duty?r.agents.find(a=>a.id===duty.assignee):null;$('duty').textContent=duty?`Assigned to ${owner?.name??duty.assignee}. Still unfinished.`:'The collection has not yet created this review duty.';$('duty-status').textContent=duty?.status??'NOT YET';$('technical-summary').textContent=`Core 0.2.2 · ${r.events.length} events (${r.recordedPrefixEvents} recorded + ${r.experimentEvents} experimental) · history time ${r.head.canonicalTime} · no wall-clock freshness claim.`;$('technical').textContent=JSON.stringify({decision:r.decision,code:r.code,actorId:r.actorId,action:r.action,resource:r.resource,head:r.head,scope:r.scope,coreResult:r.coreResult},null,2);$('timeline').replaceChildren(...r.events.map((e,i)=>el('li',`${i}: ${e.type} · ${i<r.recordedPrefixEvents?'recorded':'experiment'}`)));
 if(pinned)$('comparison').textContent=`Kept: ${pinned.name} / ${pinned.actor} / ${pinned.action}: ${pinned.decision}. Now: ${c.names[c.actor]} / ${ACTIONS[c.operation][1]}: ${r.decision}. ${r.duties.length?'The review is still '+r.duties[0].status+'.':''}`;
}
function run(){
 if(!$('names').reportValidity())return Promise.resolve(false);
 clearResult('Checking the scenario in a fresh worker…');let raw;try{raw=JSON.stringify(c);c=parseCase(raw);}catch(e){error(e.message);return Promise.resolve(false);}const ticket=serial;$('run').disabled=true;$('decision').textContent='Checking…';
 return new Promise(resolve=>{finishPending=resolve;let settled=false;const w=new Worker('./worker.js',{type:'module'});worker=w;const finish=(ok,message)=>{if(settled)return;settled=true;clearTimeout(timeout);w.terminate();if(worker===w)worker=null;if(ticket!==serial){resolve(false);return;}finishPending=null;if(message)error(message);resolve(ok);};const timeout=setTimeout(()=>finish(false,'This run took too long. Reduce the team or permissions and try again. No result has been accepted.'),20000);
 w.onerror=()=>finish(false,'The browser could not load or run the engine. Check the connection, then try again.');w.onmessage=({data})=>{if(ticket!==serial)return;try{if(typeof data!=='string'||data.length>4000000)throw Error('Unexpected engine response.');const m=JSON.parse(data);if(m.ready){w.postMessage(raw);return;}if(!m.ok){finish(false,m.error);return;}showResult(m.result);finish(true);}catch(e){finish(false,e.message);}};
 });
}
function preset(which){c=defaultCase();if(which==='revoked'){c.name='The job without a key';c.withdrawReview=true;}if(which==='old'){c.name='The old helper tries again';c.actor=0;c.operation=1;}if(which==='team'){c.name='The incident room';c.names=['Alex','Bea','Casey','Devon','Emery','Frankie','Gray','Harper'];c.actor=2;c.operation=2;c.roles=[{role:0,agent:2,operations:[2,3]},{role:3,agent:3,operations:[4]},{role:4,agent:4,operations:[6]},{role:5,agent:5,operations:[8,9]},{role:6,agent:6,operations:[10]}];}if(which==='stop'){c.name='A clear stop rule';c.deny=true;}if(which==='expiry'){c.name='A temporary permission expires';c.actor=2;c.operation=4;c.grants=[{agent:2,operation:4,revoked:false,expired:true}];}changed();renderForm();run();}
$('story').onclick=()=>mode(false);$('workshop').onclick=()=>mode(true);function mode(advanced){$('workbench').hidden=!advanced;document.querySelector('.layout').classList.toggle('advanced',advanced);$('story').setAttribute('aria-pressed',String(!advanced));$('workshop').setAttribute('aria-pressed',String(advanced));}
$('case-name').oninput=e=>{c.name=e.target.value;changed();};$('actor').onchange=e=>{c.actor=Number(e.target.value);changed();};$('operation').onchange=e=>{c.operation=Number(e.target.value);changed();};$('withdraw').onchange=e=>{c.withdrawReview=e.target.checked;changed();};$('deny').onchange=e=>{c.deny=e.target.checked;changed();};$('run').onclick=()=>{playEpoch++;playing=false;$('play').textContent='Play the handover';run();};$('preset').onchange=e=>preset(e.target.value);$('reset').onclick=()=>preset($('preset').value);
$('names').onchange=e=>{const names=e.target.value.split('\n').map(s=>s.trim()).filter(Boolean);try{parseCase(JSON.stringify({...c,names,actor:Math.min(c.actor,names.length-1)}));}catch(err){$('names').setCustomValidity(err.message);error(err.message);return;}$('names').setCustomValidity('');c.names=names;c.actor=Math.min(c.actor,names.length-1);changed();renderForm();};$('add-agent').onclick=()=>{if(c.names.length>=12)return;let n=c.names.length+1;while(c.names.includes('Helper '+n))n++;c.names.push('Helper '+n);changed();renderForm();};$('add-grant').onclick=()=>{if(c.grants.length>=32)return;c.grants.push({agent:c.actor,operation:c.operation,revoked:false,expired:false});changed();renderForm();};
for(const b of document.querySelectorAll('[data-step]'))b.onclick=()=>{changed();c.step=Number(b.dataset.step);renderStep();run();};$('previous').onclick=()=>{changed();c.step=Math.max(0,c.step-1);renderStep();run();};$('next').onclick=()=>{changed();c.step=Math.min(3,c.step+1);renderStep();run();};$('play').onclick=async()=>{if(playing){changed();return;}playing=true;const epoch=++playEpoch;$('play').textContent='Pause';for(let i=0;i<4&&playing&&epoch===playEpoch;i++){c.step=i;renderStep();const ok=await run();if(!ok)break;await new Promise(r=>setTimeout(r,1800));}if(epoch===playEpoch){playing=false;$('play').textContent='Play the handover';}};
$('pin').onclick=()=>{if(!last)return;pinned={name:c.name,actor:c.names[c.actor],action:ACTIONS[c.operation][1],decision:last.decision};$('comparison').textContent=`Kept ${pinned.actor}: ${pinned.action} — ${pinned.decision}. Change a choice and run again.`;};
function download(name,value){const u=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=el('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
$('export-case').onclick=()=>{if(!$('names').reportValidity())return;try{const value=parseCase(JSON.stringify(c));download('continuity-scenario.json',value);}catch(e){error(e.message);}};$('export-result').onclick=()=>{if(last)download('continuity-result.json',{scenario:c,result:last});};$('import-case').onchange=async e=>{const file=e.target.files?.[0];if(!file)return;try{if(file.size>32768)throw Error('Choose a scenario file smaller than 32 KB.');c=parseCase(await file.text());changed();renderForm();mode(true);await run();}catch(err){error(err.message);}finally{e.target.value='';}};
renderForm();run();
