import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';
import { createHash } from 'node:crypto';
import * as profile from '../packages/core-0.2/src/core/portable-adapter-engine.ts';
import { canonicalEncode, hashCanonical } from '../packages/core-0.2/src/core/canonical.ts';
import { CORE_EVENT_TYPES, coreEventTypeRank, validateCanonicalEventShape, isCoreSchemaLimitFailure } from '../packages/core-0.2/src/core/event-schema.ts';
import { portableAdministrativeTransitionEffect } from '../packages/core-0.2/src/core/portable-administration-codec.ts';

// Frozen R01 policy objects and shape-result hashes; these are never regenerated by the test.
const baseline = {
  "policies": {
    "PORTABLE_ADAPTER_POLICY_HASH": {
      "edition": "E1",
      "hash": "0x00c3498e2744943663475d0187ca979cdd09763b88427781883693c4b8c163a7",
      "profiles": [
        {
          "profileId": "adapter:local-evidence-packet",
          "profileVersion": "1",
          "descriptorHash": "0xd4b988c1f23603cf35d9abd0db5a7eb56ef7a5fba1a8f3e904490c1ce4458d64"
        },
        {
          "profileId": "adapter:simulated",
          "profileVersion": "1",
          "descriptorHash": "0xa9f3354121fdbc4d983093e34684d5ddc841874f8fccadbafe30df65f2e16ac2"
        }
      ]
    },
    "PORTABLE_ADAPTER_POLICY_E2_HASH": {
      "edition": "E2",
      "hash": "0x22eb40a92e50c998e007f67f0af0bc584e25f4b21c9bd802cbebe5981828810e",
      "profiles": [
        {
          "profileId": "adapter:local-evidence-packet",
          "profileVersion": "1",
          "descriptorHash": "0xd4b988c1f23603cf35d9abd0db5a7eb56ef7a5fba1a8f3e904490c1ce4458d64"
        },
        {
          "profileId": "adapter:local-synthetic-endpoint-state",
          "profileVersion": "1",
          "descriptorHash": "0x486bad2029389663117b06785e641f3a6ec2a90ca89b60e95267965ddc5977ed"
        },
        {
          "profileId": "adapter:simulated",
          "profileVersion": "1",
          "descriptorHash": "0xa9f3354121fdbc4d983093e34684d5ddc841874f8fccadbafe30df65f2e16ac2"
        }
      ]
    },
    "PORTABLE_ADAPTER_POLICY_E3_HASH": {
      "edition": "E3",
      "hash": "0xda1ac0f7af67e35a2acd3e213089bafd65204e4bb50e6a0823f8e7e941168666",
      "profiles": [
        {
          "profileId": "adapter:local-document-release",
          "profileVersion": "1",
          "descriptorHash": "0x9749dc03bd4db3c4a1f8eba707fa5ab49ea02f0a948b22697a3b7152a01393bc"
        },
        {
          "profileId": "adapter:local-evidence-packet",
          "profileVersion": "1",
          "descriptorHash": "0xd4b988c1f23603cf35d9abd0db5a7eb56ef7a5fba1a8f3e904490c1ce4458d64"
        },
        {
          "profileId": "adapter:local-synthetic-endpoint-state",
          "profileVersion": "1",
          "descriptorHash": "0x486bad2029389663117b06785e641f3a6ec2a90ca89b60e95267965ddc5977ed"
        },
        {
          "profileId": "adapter:simulated",
          "profileVersion": "1",
          "descriptorHash": "0xa9f3354121fdbc4d983093e34684d5ddc841874f8fccadbafe30df65f2e16ac2"
        }
      ]
    },
    "PORTABLE_ADAPTER_POLICY_E4_HASH": {
      "edition": "E4",
      "hash": "0xe332eb30cd57a0106582649f124d33d17272096cd42b96d9155b53594a3894a5",
      "profiles": [
        {
          "profileId": "adapter:local-document-release",
          "profileVersion": "1",
          "descriptorHash": "0x9749dc03bd4db3c4a1f8eba707fa5ab49ea02f0a948b22697a3b7152a01393bc"
        },
        {
          "profileId": "adapter:local-evidence-packet",
          "profileVersion": "1",
          "descriptorHash": "0xd4b988c1f23603cf35d9abd0db5a7eb56ef7a5fba1a8f3e904490c1ce4458d64"
        },
        {
          "profileId": "adapter:local-synthetic-endpoint-state",
          "profileVersion": "1",
          "descriptorHash": "0x486bad2029389663117b06785e641f3a6ec2a90ca89b60e95267965ddc5977ed"
        },
        {
          "profileId": "adapter:remote-service-report",
          "profileVersion": "1",
          "descriptorHash": "0xa86975f20bd2cac74ab19ccfed948a18c8c85c05407ca925dc685ac4b5d460c0"
        },
        {
          "profileId": "adapter:simulated",
          "profileVersion": "1",
          "descriptorHash": "0xa9f3354121fdbc4d983093e34684d5ddc841874f8fccadbafe30df65f2e16ac2"
        }
      ]
    }
  },
  "oldTypes": [
    "DEPLOYMENT_INITIALIZED",
    "PRINCIPAL_CREATED",
    "AGENT_CREATED",
    "ROLE_CREATED",
    "SUCCESSION_RULE_DECLARED",
    "AGENT_APPOINTED",
    "AGENT_UNAPPOINTED",
    "ROLE_TRANSFERRED",
    "RUNTIME_SESSION_ADMITTED",
    "CONTROL_EPOCH_ADVANCED",
    "AUTHORITY_GRANTED",
    "AUTHORITY_REVOKED",
    "TRANSACTION_INTENT_DECLARED",
    "TRANSACTION_INTENT_ADMITTED",
    "TRANSACTION_INTENT_CONSUMED",
    "TRANSACTION_OUTCOME_RECORDED",
    "RECEIPT_RECORDED",
    "OBLIGATION_CREATED",
    "OBLIGATION_PERFORMANCE_ASSIGNED",
    "OBLIGATION_STATUS_RECORDED",
    "AGENT_TERMINATED"
  ],
  "fixtureSha256": "e318a05ded2b2b889509e562fb5974dfe68f527ed6617117af13b10fc7fcb520",
  "shapeHashes": [
    "0x8d7647d30fe43a3339c15621e77e931bb03087bb0c0750e59210ec919a6a0e2e",
    "0x3163276513983ef0964387ebf8710c51d68ba1e8215401a2bbc238c400d7def8",
    "0x05cd1b07dd7a2db67c6f7b26a35e9912f65c8fcba2a46c15f67a7a3d819f70fd",
    "0x12837b241b934d4c642c5072a90c556a87dace8f8045f6645bdb7176f622065e",
    "0x9ce514dfe894427f2d2d113bc2bbaa471683579e4d0308166ea26dd6a30cd19d",
    "0xe2f5c49e313a4398ed82431c6798a710840e3e419f790331e5f043cac85b952e",
    "0x187a1b5c3be00c2f3815d554ce8d8c6e783cd66441104ee19e38e5a8db05326d",
    "0x7b1546701f0d1fc8e44b5bd1649a0bfdf856e56d6385a2a0c139bb81f8a2f48e",
    "0xc0a7c59062526150f4d3f845dde37a053d6a3615c087afde0a3fc6f0cb45ddcf",
    "0xea350a6f0b85d47e4a4dc88da678c92297ef9e76a54bd8f19e290725cce03270",
    "0x528190c1849f2ad916a4477125c64088894b00c6971621cca7b7c6fdb33bbecb",
    "0x0118ff9fd6d9d079d73dbb239d84d7dd166d88491adf84f39a74a9c335e5977c",
    "0x421fd9fc1a09e3babeedec13e5fcdc0616d3dac96449833260eebaa89dfdacda",
    "0x4c5db1a58943f5cb850c41114e15b6615739b1e67db74f7427341b519a2376dd",
    "0x39a324f36af4378829c5d130f805e2595a0b7a625fc76a451c07d8718c148614",
    "0x3eac87a45daf0a3778b76d765b05fec589e29a4ac2d6911de96a8deb261593c8",
    "0xbb831eb4f457d0b2818e0071ba35666b3549f29523e9acfb4747975b83aff1ce",
    "0xeda1a05e648c690087060ac5dd08eebbbbc8d10bfd896b33e19fac0603efa165",
    "0xbf1b3c33137602c4e354162300079e81204228ae2e2acab5e34b81e26c1a25bf",
    "0x584d7d465e1f83a12183fd214d6640802da7ae12a59044da421627c88ddd98b1",
    "0xd9b2282a7be12dd46772a35ec9279c4bd320376a1713f8178c5b77f773e822e9",
    "0x79180cf5d44e70bb6207c724aeaba635012f6bc0ccb2ed4eb98af945c6ee27d0",
    "0xb41acc9e883b6cc9aeac1a6887748244703d9b485ea0f4e6bcd0ed12245e5cfb",
    "0x4f0aa65b6f41df55650b637e6200ac165e803b8cfb9b888f1d9d3353afb628d8",
    "0x65aa20d099a5856b92b1422851e9e612a6dbe03ae3348bd93e9e8fa2af8a9c68",
    "0xb8293a1e2c410a250af95ec7489679cf813cdeddf683ed8cdef4f43fb83f7151"
  ],
  "count": 26,
  "hasObligation": true
};

test('R02 schemas preserve legacy identities, bind complete effects and reject malformed bounded inputs', () => {
let checks = 0;
const count = () => checks++;
for (const key of ['PORTABLE_ADAPTER_POLICY_HASH', 'PORTABLE_ADAPTER_POLICY_E2_HASH', 'PORTABLE_ADAPTER_POLICY_E3_HASH', 'PORTABLE_ADAPTER_POLICY_E4_HASH']) {
  assert.equal(profile[key], baseline.policies[key].hash);
  assert.deepEqual(profile.resolvePortableAdapterPolicy(profile[key]), baseline.policies[key]);
  count();
}
const e5 = profile.resolvePortableAdapterPolicy(profile.PORTABLE_ADAPTER_POLICY_E5_HASH);
assert.equal(e5.edition, 'E5');
assert.equal(e5.semanticExtension, 'continuity-attempt-observation-duty/1');
assert.deepEqual(e5.profiles, profile.resolvePortableAdapterPolicy(profile.PORTABLE_ADAPTER_POLICY_E4_HASH).profiles);
assert.notEqual(e5.hash, profile.PORTABLE_ADAPTER_POLICY_E4_HASH);
assert.equal(Object.values(baseline.policies).some(policy => policy.hash === e5.hash), false);
assert.deepEqual(CORE_EVENT_TYPES.slice(0, baseline.oldTypes.length), baseline.oldTypes);
count();

const fixtureBytes = readFileSync(new URL('../tests/fixtures/original-core/cases/core02-packet-r1/export/history.json', import.meta.url));
assert.equal(createHash('sha256').update(fixtureBytes).digest('hex'), baseline.fixtureSha256);
const fixture = JSON.parse(fixtureBytes,
  (_key, value) => value && typeof value === 'object' && typeof value['$continuity.bigint'] === 'string' ? BigInt(value['$continuity.bigint']) : value);
assert.equal(fixture.length, baseline.count);
for (let index = 0; index < fixture.length; index++) {
  assert.equal(hashCanonical(validateCanonicalEventShape(fixture[index])), baseline.shapeHashes[index]);
  count();
}
const oldCreated = fixture.find(event => event.type === 'OBLIGATION_CREATED');
const baseAuth = oldCreated.data.administrativeAuthorization;
const domain = baseAuth.challenge.domain;
const hash = char => `0x${char.repeat(64)}`;
const idempotencyKey = profile.derivePortableAdapterIdempotencyKey(domain, 'intent:r02');
const submissionFingerprint = hash('b');
const admissionHead = { hash: hash('c'), position: 7, canonicalTime: 10 };
const identity = { adapterProfile: profile.approvedPortableAdapterProfileForPolicy(e5.hash, profile.REMOTE_SERVICE_REPORT_ADAPTER_ID),
  domain, intentId: 'intent:r02', admissionHead, idempotencyKey, submissionFingerprint, durableEventHistoryHash: admissionHead.hash,
  adapterNoEffectReference: profile.derivePortableAdapterNoEffectReference(idempotencyKey, submissionFingerprint) };
const acknowledgment = profile.createRemoteServiceReportAcknowledgment(identity, hash('d'));
const record = { dutyId: 'duty:r02', sourceIntentId: 'intent:r02', sourceAdmissionEventId: 'admission:r02', durableRoleId: 'role:r02',
  creationRoleTenureId: 'tenure:r02', description: 'Resolve the attempt', deadline: 100, performanceAssigneeId: 'agent:r02', status: 'OPEN' };
const bodies = [
  ['OUTCOME_OBSERVATION_RECORDED', { intentId: 'intent:r02', sourceAdmissionEventId: 'admission:r02', acknowledgment, actorId: 'agent:r02' }],
  ['ATTEMPT_DUTY_CREATED', { record, actorId: 'agent:r02' }],
  ['ATTEMPT_DUTY_ASSIGNED', { dutyId: 'duty:r02', fromAgentId: 'agent:prior', toAgentId: 'agent:r02', actorId: 'agent:r02' }],
];
const events = bodies.map(([type, body], index) => {
  const administrativeAuthorization = structuredClone(baseAuth);
  administrativeAuthorization.challenge.transitionEventType = type;
  return { id: `event:${index}`, type, timestamp: 50, data: { ...body, administrativeAuthorization } };
});
for (let i = 0; i < events.length; i++) {
  const event = events[i];
  const validated = validateCanonicalEventShape(event);
  assert.equal(validated.ok, true, JSON.stringify(validated));
  assert.equal(coreEventTypeRank(event.type), 21 + i);
  const effect = portableAdministrativeTransitionEffect(validated.event);
  assert.deepEqual(Object.keys(effect).sort(), ['transitionEventType', ...Object.keys(bodies[i][1])].sort());
  for (const [key, value] of Object.entries(bodies[i][1])) assert.equal(canonicalEncode(effect[key]), canonicalEncode(value));
  assert.equal(Object.isFrozen(effect), true);
  for (const field of Object.keys(event.data)) {
    for (const mode of ['missing', 'undefined']) {
      const changed = structuredClone(event);
      if (mode === 'missing') delete changed.data[field]; else changed.data[field] = undefined;
      assert.equal(validateCanonicalEventShape(changed).ok, false, `${event.type} ${field} ${mode}`);
      count();
    }
  }
  for (const extra of [null, undefined]) {
    const changed = structuredClone(event); changed.data.extra = extra;
    assert.equal(validateCanonicalEventShape(changed).ok, false);
    count();
  }
  const longActor = structuredClone(event); longActor.data.actorId = 'a'.repeat(257);
  const invalid = validateCanonicalEventShape(longActor);
  assert.equal(invalid.ok, false);
  assert.equal(isCoreSchemaLimitFailure(invalid), true);
  count();
}
for (const field of Object.keys(record)) {
  for (const mode of ['missing', 'undefined']) {
    const changed = structuredClone(events[1]);
    if (mode === 'missing') delete changed.data.record[field]; else changed.data.record[field] = undefined;
    assert.equal(validateCanonicalEventShape(changed).ok, false, `${field} ${mode}`);
    count();
  }
  const changed = structuredClone(events[1]);
  changed.data.record[field] = field === 'deadline' ? record.deadline + 1 : `${record[field]}!`;
  assert.notEqual(hashCanonical(portableAdministrativeTransitionEffect(changed)), hashCanonical(portableAdministrativeTransitionEffect(events[1])));
  count();
}
for (const value of ['DISCHARGED', 'OUTCOME_UNKNOWN', '', undefined]) {
  const changed = structuredClone(events[1]); changed.data.record.status = value;
  assert.equal(validateCanonicalEventShape(changed).ok, false);
  count();
}
for (const mutate of [
  event => { event.data.record.extra = undefined; },
  event => { event.data.record.description = 'x'.repeat(4097); },
  event => { event.data.record.deadline = -1; },
  event => { event.data.record.sourceAdmissionEventId = 'x'.repeat(257); },
]) {
  const changed = structuredClone(events[1]); mutate(changed);
  assert.equal(validateCanonicalEventShape(changed).ok, false);
  count();
}
for (const mutate of [
  event => { event.data.acknowledgment.result.reportDigest.extra = undefined; },
  event => { event.data.acknowledgment.result.reportDigest.algorithm = 'keccak256'; },
  event => { event.data.acknowledgment.schemaVersion = profile.PORTABLE_ADAPTER_ACKNOWLEDGMENT_VERSION; },
]) {
  const changed = structuredClone(events[0]); mutate(changed);
  assert.equal(validateCanonicalEventShape(changed).ok, false);
  count();
}
const changedObservation = structuredClone(events[0]);
changedObservation.data.acknowledgment.result.reportDigest.value = hash('e');
assert.notEqual(hashCanonical(portableAdministrativeTransitionEffect(changedObservation)), hashCanonical(portableAdministrativeTransitionEffect(events[0])));
count();
console.log(JSON.stringify({ status: 'PASS', checks, newEventRanks: events.map(e => [e.type, coreEventTypeRank(e.type)]), e5Hash: e5.hash,
  limits: 'Shape/projection/profile checks only; fixture signatures are not re-authorized and replay semantics are tested separately.' }, null, 2));
});
