'use strict';
const tabs=[...document.querySelectorAll('[data-tab]')];
function selectTab(button){document.body.dataset.view=button.dataset.tab;for(const tab of tabs){const selected=tab===button;tab.setAttribute('aria-selected',String(selected));tab.tabIndex=selected?0:-1;document.getElementById(tab.dataset.tab).hidden=!selected;}}
for(const button of tabs){button.addEventListener('click',()=>selectTab(button));button.addEventListener('keydown',event=>{let i=tabs.indexOf(button);if(event.key==='ArrowRight')i=(i+1)%tabs.length;else if(event.key==='ArrowLeft')i=(i+tabs.length-1)%tabs.length;else if(event.key==='Home')i=0;else if(event.key==='End')i=tabs.length-1;else return;event.preventDefault();selectTab(tabs[i]);tabs[i].focus();});}
const stages=[
 ['01 / COLLECTION','Permission precedes the action.','A has an explicit collection grant. Core admits its request, the simulator acknowledges it, and a separate review duty is recorded as OPEN.','Authorized to collect','Not yet assigned','Assigned to Agent A'],
 ['02 / REPLACEMENT','New agent. Explicit handover.','The operator advances A’s control epoch, terminates A in the protocol, transfers the role, admits B’s session, and assigns the unfinished duty to B. This does not kill an OS process.','No longer current','Duty assigned','Assigned to Agent B'],
 ['03 / REFUSAL','The old signature is not enough.','After handover, the operator also revokes A’s collection grant. A submits an obsolete signed request. Current admission denies it before the executor is invoked.','Old request denied','Duty assigned','Assigned to Agent B'],
 ['04 / CONTINUATION','The duty survives. Power stays bounded.','B holds the same OPEN investigation duty. Its independently declared review grant determines whether it may review. B has no collection power. Use the comparison to inspect both recorded outcomes.','Authority withdrawn','Review power checked','Assigned to Agent B']
];
let step=0;const id=x=>document.getElementById(x);
function showStep(i){step=i;const [kicker,title,description,a,b,assignee]=stages[i];id('stage-kicker').textContent=kicker;id('stage-title').textContent=title;id('stage-description').textContent=description;id('a-status').textContent=a;id('b-status').textContent=b;id('assignee').textContent=assignee;id('agent-a').classList.toggle('inactive',i>0);id('agent-b').classList.toggle('inactive',i===0);id('previous').disabled=i===0;id('next').disabled=i===3;id('step-count').textContent=`Stage ${i+1} of 4`;for(const button of document.querySelectorAll('[data-step]')){if(Number(button.dataset.step)===i)button.setAttribute('aria-current','step');else button.removeAttribute('aria-current');}}
for(const b of document.querySelectorAll('[data-step]'))b.addEventListener('click',()=>showStep(Number(b.dataset.step)));
id('previous').addEventListener('click',()=>showStep(Math.max(0,step-1)));id('next').addEventListener('click',()=>showStep(Math.min(3,step+1)));
for(const radio of document.querySelectorAll('[name=permission]'))radio.addEventListener('change',()=>{const allowed=radio.value==='allow';id('review-decision').textContent=allowed?'ALLOW':'DENY';id('review-decision').className=allowed?'allow':'deny';id('policy-explanation').textContent=allowed?'B’s independent grant allows review. It inherits no collection power.':'B’s review grant was revoked after handover. The OPEN duty remains; responsibility supplies no permission.';const base=`evidence/simulated-${radio.value}/`;id('decision-evidence').href=base+'successor-authority.json';id('run-evidence').href=base+'result.json';id('stale-evidence').href=base+'stale-request.json';});
for(const b of document.querySelectorAll('[data-copy]'))b.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(id(b.dataset.copy).textContent);b.textContent='Copied';}catch{b.textContent='Select text to copy';}setTimeout(()=>b.textContent='Copy commands',2500);});
